datasource {
  jdbc-url = "jdbc:postgresql://localhost:5432/conduit"
  user = "conduit"
  password = "conduit"
  pool-size = 10
  connection-test-query = "SELECT 1"
  driver-class = "org.postgresql.Driver"
  connection-timeout = 60 seconds
}
migration {
  init-sql = "SET search_path TO public"
  locations = ["classpath:migrations/schema"]
  parameters = {}
  placeholders = {}
  allow-clean = false
}
